### ISSUE TITLE
Can't locate an import

### ISSUE THREAD

**Issue by rahul70392** [switchboard-xyz/vrf-flip#2]
In the file  app/src/data/providers/ApiProvider.tsx / , you have imported  -  ../../api . I am not able to locate it, is it gitignored?

**Comment by jessupjn** [comment]
```
cd app
yarn install && yarn build
```
Within the `app/` directory there is a `prebuild` script that copies over the files to run. Swapping `yarn build` for `yarn start` should work too I'd expect.
